// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.36.11
// 	protoc        v3.21.12
// source: proto/boards.proto

package boardspb

import (
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	emptypb "google.golang.org/protobuf/types/known/emptypb"
	reflect "reflect"
	sync "sync"
	unsafe "unsafe"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

type Board struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Id            int64                  `protobuf:"varint,1,opt,name=id,proto3" json:"id,omitempty"`
	Name          string                 `protobuf:"bytes,2,opt,name=name,proto3" json:"name,omitempty"`
	Description   string                 `protobuf:"bytes,3,opt,name=description,proto3" json:"description,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *Board) Reset() {
	*x = Board{}
	mi := &file_proto_boards_proto_msgTypes[0]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *Board) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*Board) ProtoMessage() {}

func (x *Board) ProtoReflect() protoreflect.Message {
	mi := &file_proto_boards_proto_msgTypes[0]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use Board.ProtoReflect.Descriptor instead.
func (*Board) Descriptor() ([]byte, []int) {
	return file_proto_boards_proto_rawDescGZIP(), []int{0}
}

func (x *Board) GetId() int64 {
	if x != nil {
		return x.Id
	}
	return 0
}

func (x *Board) GetName() string {
	if x != nil {
		return x.Name
	}
	return ""
}

func (x *Board) GetDescription() string {
	if x != nil {
		return x.Description
	}
	return ""
}

type CreateBoardRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Name          string                 `protobuf:"bytes,1,opt,name=name,proto3" json:"name,omitempty"`
	Description   string                 `protobuf:"bytes,2,opt,name=description,proto3" json:"description,omitempty"`
	UserId        int64                  `protobuf:"varint,3,opt,name=user_id,json=userId,proto3" json:"user_id,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *CreateBoardRequest) Reset() {
	*x = CreateBoardRequest{}
	mi := &file_proto_boards_proto_msgTypes[1]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *CreateBoardRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*CreateBoardRequest) ProtoMessage() {}

func (x *CreateBoardRequest) ProtoReflect() protoreflect.Message {
	mi := &file_proto_boards_proto_msgTypes[1]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use CreateBoardRequest.ProtoReflect.Descriptor instead.
func (*CreateBoardRequest) Descriptor() ([]byte, []int) {
	return file_proto_boards_proto_rawDescGZIP(), []int{1}
}

func (x *CreateBoardRequest) GetName() string {
	if x != nil {
		return x.Name
	}
	return ""
}

func (x *CreateBoardRequest) GetDescription() string {
	if x != nil {
		return x.Description
	}
	return ""
}

func (x *CreateBoardRequest) GetUserId() int64 {
	if x != nil {
		return x.UserId
	}
	return 0
}

type CreateBoardResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Board         *Board                 `protobuf:"bytes,1,opt,name=board,proto3" json:"board,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *CreateBoardResponse) Reset() {
	*x = CreateBoardResponse{}
	mi := &file_proto_boards_proto_msgTypes[2]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *CreateBoardResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*CreateBoardResponse) ProtoMessage() {}

func (x *CreateBoardResponse) ProtoReflect() protoreflect.Message {
	mi := &file_proto_boards_proto_msgTypes[2]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use CreateBoardResponse.ProtoReflect.Descriptor instead.
func (*CreateBoardResponse) Descriptor() ([]byte, []int) {
	return file_proto_boards_proto_rawDescGZIP(), []int{2}
}

func (x *CreateBoardResponse) GetBoard() *Board {
	if x != nil {
		return x.Board
	}
	return nil
}

type GetBoardByIDRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Id            int64                  `protobuf:"varint,1,opt,name=id,proto3" json:"id,omitempty"`
	UserId        int64                  `protobuf:"varint,2,opt,name=user_id,json=userId,proto3" json:"user_id,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *GetBoardByIDRequest) Reset() {
	*x = GetBoardByIDRequest{}
	mi := &file_proto_boards_proto_msgTypes[3]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *GetBoardByIDRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*GetBoardByIDRequest) ProtoMessage() {}

func (x *GetBoardByIDRequest) ProtoReflect() protoreflect.Message {
	mi := &file_proto_boards_proto_msgTypes[3]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use GetBoardByIDRequest.ProtoReflect.Descriptor instead.
func (*GetBoardByIDRequest) Descriptor() ([]byte, []int) {
	return file_proto_boards_proto_rawDescGZIP(), []int{3}
}

func (x *GetBoardByIDRequest) GetId() int64 {
	if x != nil {
		return x.Id
	}
	return 0
}

func (x *GetBoardByIDRequest) GetUserId() int64 {
	if x != nil {
		return x.UserId
	}
	return 0
}

type GetBoardResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Board         *Board                 `protobuf:"bytes,1,opt,name=board,proto3" json:"board,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *GetBoardResponse) Reset() {
	*x = GetBoardResponse{}
	mi := &file_proto_boards_proto_msgTypes[4]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *GetBoardResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*GetBoardResponse) ProtoMessage() {}

func (x *GetBoardResponse) ProtoReflect() protoreflect.Message {
	mi := &file_proto_boards_proto_msgTypes[4]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use GetBoardResponse.ProtoReflect.Descriptor instead.
func (*GetBoardResponse) Descriptor() ([]byte, []int) {
	return file_proto_boards_proto_rawDescGZIP(), []int{4}
}

func (x *GetBoardResponse) GetBoard() *Board {
	if x != nil {
		return x.Board
	}
	return nil
}

type UpdateBoardRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Id            int64                  `protobuf:"varint,1,opt,name=id,proto3" json:"id,omitempty"`
	Name          string                 `protobuf:"bytes,2,opt,name=name,proto3" json:"name,omitempty"`
	Description   string                 `protobuf:"bytes,3,opt,name=description,proto3" json:"description,omitempty"`
	UserId        int64                  `protobuf:"varint,4,opt,name=user_id,json=userId,proto3" json:"user_id,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *UpdateBoardRequest) Reset() {
	*x = UpdateBoardRequest{}
	mi := &file_proto_boards_proto_msgTypes[5]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *UpdateBoardRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*UpdateBoardRequest) ProtoMessage() {}

func (x *UpdateBoardRequest) ProtoReflect() protoreflect.Message {
	mi := &file_proto_boards_proto_msgTypes[5]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use UpdateBoardRequest.ProtoReflect.Descriptor instead.
func (*UpdateBoardRequest) Descriptor() ([]byte, []int) {
	return file_proto_boards_proto_rawDescGZIP(), []int{5}
}

func (x *UpdateBoardRequest) GetId() int64 {
	if x != nil {
		return x.Id
	}
	return 0
}

func (x *UpdateBoardRequest) GetName() string {
	if x != nil {
		return x.Name
	}
	return ""
}

func (x *UpdateBoardRequest) GetDescription() string {
	if x != nil {
		return x.Description
	}
	return ""
}

func (x *UpdateBoardRequest) GetUserId() int64 {
	if x != nil {
		return x.UserId
	}
	return 0
}

type UpdateBoardResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Board         *Board                 `protobuf:"bytes,1,opt,name=board,proto3" json:"board,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *UpdateBoardResponse) Reset() {
	*x = UpdateBoardResponse{}
	mi := &file_proto_boards_proto_msgTypes[6]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *UpdateBoardResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*UpdateBoardResponse) ProtoMessage() {}

func (x *UpdateBoardResponse) ProtoReflect() protoreflect.Message {
	mi := &file_proto_boards_proto_msgTypes[6]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use UpdateBoardResponse.ProtoReflect.Descriptor instead.
func (*UpdateBoardResponse) Descriptor() ([]byte, []int) {
	return file_proto_boards_proto_rawDescGZIP(), []int{6}
}

func (x *UpdateBoardResponse) GetBoard() *Board {
	if x != nil {
		return x.Board
	}
	return nil
}

type DeleteBoardRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Id            int64                  `protobuf:"varint,1,opt,name=id,proto3" json:"id,omitempty"`
	UserId        int64                  `protobuf:"varint,2,opt,name=user_id,json=userId,proto3" json:"user_id,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *DeleteBoardRequest) Reset() {
	*x = DeleteBoardRequest{}
	mi := &file_proto_boards_proto_msgTypes[7]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *DeleteBoardRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*DeleteBoardRequest) ProtoMessage() {}

func (x *DeleteBoardRequest) ProtoReflect() protoreflect.Message {
	mi := &file_proto_boards_proto_msgTypes[7]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use DeleteBoardRequest.ProtoReflect.Descriptor instead.
func (*DeleteBoardRequest) Descriptor() ([]byte, []int) {
	return file_proto_boards_proto_rawDescGZIP(), []int{7}
}

func (x *DeleteBoardRequest) GetId() int64 {
	if x != nil {
		return x.Id
	}
	return 0
}

func (x *DeleteBoardRequest) GetUserId() int64 {
	if x != nil {
		return x.UserId
	}
	return 0
}

var File_proto_boards_proto protoreflect.FileDescriptor

const file_proto_boards_proto_rawDesc = "" +
	"\n" +
	"\x12proto/boards.proto\x12\x06boards\x1a\x1bgoogle/protobuf/empty.proto\"M\n" +
	"\x05Board\x12\x0e\n" +
	"\x02id\x18\x01 \x01(\x03R\x02id\x12\x12\n" +
	"\x04name\x18\x02 \x01(\tR\x04name\x12 \n" +
	"\vdescription\x18\x03 \x01(\tR\vdescription\"c\n" +
	"\x12CreateBoardRequest\x12\x12\n" +
	"\x04name\x18\x01 \x01(\tR\x04name\x12 \n" +
	"\vdescription\x18\x02 \x01(\tR\vdescription\x12\x17\n" +
	"\auser_id\x18\x03 \x01(\x03R\x06userId\":\n" +
	"\x13CreateBoardResponse\x12#\n" +
	"\x05board\x18\x01 \x01(\v2\r.boards.BoardR\x05board\">\n" +
	"\x13GetBoardByIDRequest\x12\x0e\n" +
	"\x02id\x18\x01 \x01(\x03R\x02id\x12\x17\n" +
	"\auser_id\x18\x02 \x01(\x03R\x06userId\"7\n" +
	"\x10GetBoardResponse\x12#\n" +
	"\x05board\x18\x01 \x01(\v2\r.boards.BoardR\x05board\"s\n" +
	"\x12UpdateBoardRequest\x12\x0e\n" +
	"\x02id\x18\x01 \x01(\x03R\x02id\x12\x12\n" +
	"\x04name\x18\x02 \x01(\tR\x04name\x12 \n" +
	"\vdescription\x18\x03 \x01(\tR\vdescription\x12\x17\n" +
	"\auser_id\x18\x04 \x01(\x03R\x06userId\":\n" +
	"\x13UpdateBoardResponse\x12#\n" +
	"\x05board\x18\x01 \x01(\v2\r.boards.BoardR\x05board\"=\n" +
	"\x12DeleteBoardRequest\x12\x0e\n" +
	"\x02id\x18\x01 \x01(\x03R\x02id\x12\x17\n" +
	"\auser_id\x18\x02 \x01(\x03R\x06userId2\xa9\x02\n" +
	"\rBoardsService\x12F\n" +
	"\vCreateBoard\x12\x1a.boards.CreateBoardRequest\x1a\x1b.boards.CreateBoardResponse\x12E\n" +
	"\fGetBoardByID\x12\x1b.boards.GetBoardByIDRequest\x1a\x18.boards.GetBoardResponse\x12F\n" +
	"\vUpdateBoard\x12\x1a.boards.UpdateBoardRequest\x1a\x1b.boards.UpdateBoardResponse\x12A\n" +
	"\vDeleteBoard\x12\x1a.boards.DeleteBoardRequest\x1a\x16.google.protobuf.EmptyB\x1dZ\x1binternal/pb/boards;boardspbb\x06proto3"

var (
	file_proto_boards_proto_rawDescOnce sync.Once
	file_proto_boards_proto_rawDescData []byte
)

func file_proto_boards_proto_rawDescGZIP() []byte {
	file_proto_boards_proto_rawDescOnce.Do(func() {
		file_proto_boards_proto_rawDescData = protoimpl.X.CompressGZIP(unsafe.Slice(unsafe.StringData(file_proto_boards_proto_rawDesc), len(file_proto_boards_proto_rawDesc)))
	})
	return file_proto_boards_proto_rawDescData
}

var file_proto_boards_proto_msgTypes = make([]protoimpl.MessageInfo, 8)
var file_proto_boards_proto_goTypes = []any{
	(*Board)(nil),               // 0: boards.Board
	(*CreateBoardRequest)(nil),  // 1: boards.CreateBoardRequest
	(*CreateBoardResponse)(nil), // 2: boards.CreateBoardResponse
	(*GetBoardByIDRequest)(nil), // 3: boards.GetBoardByIDRequest
	(*GetBoardResponse)(nil),    // 4: boards.GetBoardResponse
	(*UpdateBoardRequest)(nil),  // 5: boards.UpdateBoardRequest
	(*UpdateBoardResponse)(nil), // 6: boards.UpdateBoardResponse
	(*DeleteBoardRequest)(nil),  // 7: boards.DeleteBoardRequest
	(*emptypb.Empty)(nil),       // 8: google.protobuf.Empty
}
var file_proto_boards_proto_depIdxs = []int32{
	0, // 0: boards.CreateBoardResponse.board:type_name -> boards.Board
	0, // 1: boards.GetBoardResponse.board:type_name -> boards.Board
	0, // 2: boards.UpdateBoardResponse.board:type_name -> boards.Board
	1, // 3: boards.BoardsService.CreateBoard:input_type -> boards.CreateBoardRequest
	3, // 4: boards.BoardsService.GetBoardByID:input_type -> boards.GetBoardByIDRequest
	5, // 5: boards.BoardsService.UpdateBoard:input_type -> boards.UpdateBoardRequest
	7, // 6: boards.BoardsService.DeleteBoard:input_type -> boards.DeleteBoardRequest
	2, // 7: boards.BoardsService.CreateBoard:output_type -> boards.CreateBoardResponse
	4, // 8: boards.BoardsService.GetBoardByID:output_type -> boards.GetBoardResponse
	6, // 9: boards.BoardsService.UpdateBoard:output_type -> boards.UpdateBoardResponse
	8, // 10: boards.BoardsService.DeleteBoard:output_type -> google.protobuf.Empty
	7, // [7:11] is the sub-list for method output_type
	3, // [3:7] is the sub-list for method input_type
	3, // [3:3] is the sub-list for extension type_name
	3, // [3:3] is the sub-list for extension extendee
	0, // [0:3] is the sub-list for field type_name
}

func init() { file_proto_boards_proto_init() }
func file_proto_boards_proto_init() {
	if File_proto_boards_proto != nil {
		return
	}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: unsafe.Slice(unsafe.StringData(file_proto_boards_proto_rawDesc), len(file_proto_boards_proto_rawDesc)),
			NumEnums:      0,
			NumMessages:   8,
			NumExtensions: 0,
			NumServices:   1,
		},
		GoTypes:           file_proto_boards_proto_goTypes,
		DependencyIndexes: file_proto_boards_proto_depIdxs,
		MessageInfos:      file_proto_boards_proto_msgTypes,
	}.Build()
	File_proto_boards_proto = out.File
	file_proto_boards_proto_goTypes = nil
	file_proto_boards_proto_depIdxs = nil
}
